### ISSUE TITLE
Layer is visible 3 times

### ISSUE THREAD

**Issue by Hipska** [wazers/wme-streetviewavailability#5]
Clicking on any one only toggles the first one:

<img width="123" alt="image" src="https://user-images.githubusercontent.com/228588/75138423-785e3f80-56ea-11ea-93ff-03d340ee34ec.png">

**Comment by Glodenox** [comment]
How did you get three toggles? I'm unable to replicate that behaviour in Firefox. Going into Events mode doesn't seem to trigger this, but maybe there's another situation?

**Comment by Hipska** [comment]
Could have been a one time glitch. Was when opening the page after fresh login.
